/* Action Types related to fetch a user Info on https://randomuser.me/ */

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS';
export const GET_USER_REQUEST_FAIL = 'GET_USER_REQUEST_FAIL';

export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST';
export const GET_CONTACTS_REQUEST_SUCCESS = 'GET_CONTACTS_REQUEST_SUCCESS';
export const GET_CONTACTS_REQUEST_FAIL = 'GET_CONTACTS_REQUEST_FAIL';

export const REQUEST_DELETE_CONTACT = 'DELETE_CONTACT';
export const REQUEST_DELETE_CONTACT_SUCCESS = 'REQUEST_DELETE_CONTACT_SUCCESS';
export const REQUEST_DELETE_CONTACT_FAIL = 'REQUEST_DELETE_CONTACT_FAIL';
export const REQUEST_RESET_DELETE_CONTACT = 'REQUEST_RESET_DELETE_CONTACT';

